# Data
noise_strength: 1.e-10
n_train_ics: 500
n_val_ics: 2

# Model and training parameters
input_dim:  128
latent_dim:  3
model_order:  1
poly_order:  3
include_sine:  False

# sequential thresholding parameters
sequential_thresholding:  True
coefficient_threshold:  0.2
threshold_frequency:  10
coefficient_initialization:  'constant'

# loss function weighting
loss_weight_decoder:  1.0
loss_weight_sindy_z:  0.0
loss_weight_sindy_x:  1.e-4
loss_weight_sindy_regularization:  1.e-5

activation:  'sigmoid'
widths:  [64, 32]

# training parameters
batch_size:  1024
learning_rate:  1.e-3

print_progress:  True
print_frequency:  5

# training time cutoffs
max_epochs:  50
refinement_epochs:  10
num_experiments:  1